name: Run all LLM tests
description: Run all LLM tests, will used by both unit tests and nightly-tests. Set different envs before this test to test different models in unit tests and nightly-tests.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  llm-cpp-build:
    uses: ./.github/workflows/llm-binary-build.yml
  llm-unit-test-linux:
    needs: llm-cpp-build
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        instruction: ["AVX512"]
    runs-on: [ self-hosted, llm,"${{matrix.instruction}}", ubuntu-20.04-lts ]
    env:
      THREAD_NUM: 24
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel

      - name: Download llm binary
        uses: ./.github/actions/llm/download-llm-binary

      - name: Run LLM install (all) test
        uses: ./.github/actions/llm/setup-llm-env
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Download ckpt & original models
        uses: ./.github/actions/llm/download-models

      - name: Run LLM cli test
        uses: ./.github/actions/llm/cli-test
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Run LLM inference test
        uses: ./.github/actions/llm/inference-test
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Run LLM langchain test
        uses: ./.github/actions/llm/langchain-test
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Clean up test environment
        uses: ./.github/actions/llm/remove-llm-env
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
