name: LLM Unit Tests on Linux

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-llm-win-unittest-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'python/llm/**'
      - '.github/workflows/llm_unit_tests_linux.yml'
      - '.github/workflows/llm-binary-build.yml'
      - '.github/actions/llm/setup-llm-env/action.yml'
      - '.github/actions/llm/remove-llm-env/action.yml'
      - '.github/actions/llm/cli-test/action.yml'
      - '.github/actions/llm/inference-test/action.yml'
      - '.github/actions/llm/langchain-test/action.yml'
      - '.github/actions/llm/download-llm-binary/action.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/llm/**'
      - '.github/workflows/llm_unit_tests_linux.yml'
      - '.github/workflows/llm-binary-build.yml'
      - '.github/actions/llm/setup-llm-env/action.yml'
      - '.github/actions/llm/remove-llm-env/action.yml'
      - '.github/actions/llm/cli-test/action.yml'
      - '.github/actions/llm/inference-test/action.yml'
      - '.github/actions/llm/langchain-test/action.yml'
      - '.github/actions/llm/download-llm-binary/action.yml'
  workflow_dispatch:

env:
  INT4_CKPT_DIR: ./llm/ggml-actions/nightly
  LLAMA_INT4_CKPT_PATH: ./llm/ggml-actions/nightly/bigdl_llm_llama_q4_0.bin
  GPTNEOX_INT4_CKPT_PATH: ./llm/ggml-actions/nightly/bigdl_llm_gptneox_q4_0.bin
  BLOOM_INT4_CKPT_PATH: ./llm/ggml-actions/nightly/bigdl_llm_bloom_q4_0.bin
  STARCODER_INT4_CKPT_PATH: ./llm/ggml-actions/nightly/bigdl_llm_starcoder_q4_0.bin

  LLM_DIR: ./llm
  ORIGINAL_AUTO_MODEL_PATH: ./llm/chatglm2-6b/
  ORIGINAL_CAUSAL_MODEL_PATH: ./llm/llama-2-13b-chat-hf/
  ORIGINAL_SPEECH_MODEL_PATH: ./llm/whisper-medium/
  SPEECH_DATASET_PATH: ./llm/datasets/librispeech_asr_dummy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  llm-unit-test:
    uses: ./.github/actions/llm/all-tests