name: LLM Unit Tests on Linux

env:
  INT4_CKPT_DIR: ./llm/ggml-actions/stable
  LLAMA_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_llama_7b_q4_0.bin
  GPTNEOX_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_redpajama_7b_q4_0.bin
  BLOOM_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_bloom_7b_q4_0.bin
  STARCODER_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_santacoder_1b_q4_0.bin

  LLM_DIR: ./llm
  ORIGINAL_AUTO_MODEL_PATH: ./llm/chatglm2-6b/
  ORIGINAL_CAUSAL_MODEL_PATH: ./llm/replit-code-v1-3b/
  ORIGINAL_SPEECH_MODEL_PATH: ./llm/whisper-tiny/
  SPEECH_DATASET_PATH: ./llm/datasets/librispeech_asr_dummy


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  llm-unit-test:
    uses: ./.github/actions/llm/all-tests